/* generated by ./scorematrix.py --constexpr unit_score_nuc_lower
 * unit_score_nuc_lower.txt DO NOT EDIT */
#ifndef UNIT_SCORE_NUC_LOWER_HPP
#define UNIT_SCORE_NUC_LOWER_HPP
#include <cstdint>
    struct Unit_score_nuc_lower
{
  static constexpr const char characters[] = "acgtn";
  static constexpr size_t num_of_chars = size_t(5);
  static constexpr const char character_spec[] = "a|c|g|t|n";
  static constexpr const int8_t score_matrix[5][5] = {
      /* a  c  g  t  n */ /* a */ {2, -1, -1, -1, -1},
      /* c */ {-1, 2, -1, -1, -1}, /* g */ {-1, -1, 2, -1, -1},
      /* t */ {-1, -1, -1, 2, -1}, /* n */ {-1, -1, -1, -1, -1}};
  static constexpr const int8_t smallest_score = -1;
};
#endif
