name: "Code Check"
run-name: "Code Check"

on: 
  push:
    paths:
      - '**.cpp'
      - '**.c'
      - '**.hpp'
      - '**.h'
      - '**Makefile'
      - '**.mk'
      - '.github/workflows/code-check.yml'

  pull_request:
    paths:
      - '**.cpp'
      - '**.c'
      - '**.hpp'
      - '**.h'
      - '**Makefile'
      - '**.mk'
      - '.github/workflows/code-check.yml'

  workflow_dispatch:


jobs:
  code_check:
    name: Code Check
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: code_check
        run: make code_check
