name: "Windows CI"
run-name: "Windows CI"

on: 
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**Makefile'
      - '**.mk'
      - '.github/workflows/make-tests-windows.yml'

  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**Makefile'
      - '**.mk'
      - '.github/workflows/make-tests-windows.yml'

  workflow_dispatch:


jobs:
  test_windows_latest:
    name: Windows Tests
    runs-on: windows-latest

    env:
      CXX: clang++
      CPLUS_INCLUDE_PATH: "C:/vcpkg/installed/x64-windows/include"

    steps:
    - uses: actions/checkout@v7
    - name: Install ZLib
      run: vcpkg install zlib
    - name: Install Clang 22
      run: choco install llvm --version=22.1.7 -y --allow-downgrade || true
    - name: Add Clang 22 and ZLib DLL to PATH
      run: |
        echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        echo "C:\vcpkg\installed\x64-windows\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: make
      run: make -j4
