name: "Windows CI"
run-name: "Windows CI"

on: 
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**Makefile'
      - '**.mk'
      - '.github/workflows/make-tests-windows.yml'

  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**Makefile'
      - '**.mk'
      - '.github/workflows/make-tests-windows.yml'

  workflow_dispatch:


jobs:
  test_windows_latest:
    name: Windows Tests
    runs-on: windows-latest

    env:
      CXX: clang++
      CPLUS_INCLUDE_PATH: "C:\\vcpkg\\packages\\zlib_x64-windows\\include"

    steps:
    - uses: actions/checkout@v4
    - name: Install ZLib
      run: vcpkg install zlib
    - name: Install Clang 19
      run: choco install llvm --version=19.1.7 -y
    - name: Add Clang 19 to PATH
      run: echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: make
      run: make -j4
