name: "Linux CI"
run-name: "Linux CI"

on: 
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**Makefile'
      - '.github/workflows/make-tests-linux.yml'

  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**Makefile'
      - '.github/workflows/make-tests-linux.yml'

  workflow_dispatch: null


jobs:
  test_ubuntu_latest:
    name: Linux Tests (Ubuntu)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -j4
