name: "MacOS CI"
run-name: "MacOS CI"

on: 
  push:
    paths:
      - '**.cpp'
      - '**.c'
      - '**.hpp'
      - '**.h'
      - '**Makefile'
      - '.github/workflows/make-tests-macos.yml'

  pull_request:
    paths:
      - '**.cpp'
      - '**.c'
      - '**.hpp'
      - '**.h'
      - '**Makefile'
      - '.github/workflows/make-tests-macos.yml'

  workflow_dispatch: null


jobs:
  test_macos_latest:
    name: MacOS Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -j4
